### ISSUE TITLE
Clarification on Formula 11 in the Paper

### ISSUE THREAD

**Issue by nwt-musicApplication** [yul091/DENRL#1]
Dear author,

I have a question regarding formula 11 in your paper. You mentioned that "The higher u is, the more confident an instance I is." However, I am not quite sure about the interpretation of this statement.

In my understanding, a higher value of u seems to indicate a greater difference between the model's attention value and the BOW frequency. Alternatively, it could also suggest a smaller deviation between the prediction and the logic rules. While I can comprehend the latter interpretation, I am confused about the former.

Specifically, I am wondering why a greater difference between the model's attention value and the BOW frequency would lead to higher confidence. Could you please provide some additional clarification or explanation on this point?

Thank you in advance for your response. I am looking forward to your explanation.

**Comment by yul091** [comment]
Hi, thank you for your question! There's a miswrite in the previous preprint, we've updated it and please see the new updated version later. The u should be the sigmoid of the sum of both parts, and you're right, the lower the u, the more confident an instance is and we should prioritize it. 

The smaller MSE or other distance (e.g., KL) between the model's attention and the BOW frequency, the more likely it's correctly labeled. Let’s take a look at the example sentence “Anatolia quoted Lyor Cohen, the chief executive of the Warner Music Group, …” in Figure 4. For a start position and each target position, the model’s position-attention reflects the importance of each token in determining the head entity type and the relation between entities at the start and target positions. Suppose the start position is at “Lyor”, for a target position at “Warner”, the model should pay more attention to (1) the pattern words “chief executive of” to determine their correct relation type Company_worked, and (2) the entity words “Lyor Cohen” to determine the correct head entity type. This is exactly how attention guidance is built in BR. During BR, for the relation Company_worked, its pattern set contains corresponding patterns, e.g., {‘CEO at’, ‘manager in’, ‘chief executive of’, …} and the BoW will count tokens and their frequencies, e.g., {‘chief’: 8, ‘manager’: 14, ‘executive’: 12, ‘at’: 7, ‘of’: 16, …}. Consequently, the guidance scores for the words “chief”, “executive”, and “of” become large (after softmax computation) as they appear in the BoW with high frequencies. Also, the head entity tokens “Lyor”, and “Cohen” will be given a score of 1. In this way, both “Lyor Cohen” and “chief executive of” will be assigned a high guidance score, and we want the model’s attention to approximate such guidance distribution (by minimizing their MSE distance) so that it can better identify correct relations.

**Comment by yul091** [comment]
> Dear author,
> 
> I have a question regarding formula 11 in your paper. You mentioned that "The higher u is, the more confident an instance I is." However, I am not quite sure about the interpretation of this statement.
> 
> In my understanding, a higher value of u seems to indicate a greater difference between the model's attention value and the BOW frequency. Alternatively, it could also suggest a smaller deviation between the prediction and the logic rules. While I can comprehend the latter interpretation, I am confused about the former.
> 
> Specifically, I am wondering why a greater difference between the model's attention value and the BOW frequency would lead to higher confidence. Could you please provide some additional clarification or explanation on this point?
> 
> Thank you in advance for your response. I am looking forward to your explanation.

Hi, thank you for your question! There's a miswrite in the previous preprint, we've updated it and please see the new updated version later. The u should be the sigmoid of the sum of both parts, and you're right, the lower the u, the more confident an instance is and we should prioritize it.

The smaller MSE or other distance (e.g., KL) between the model's attention and the BOW frequency, the more likely it's correctly labeled. Let’s take a look at the example sentence “Anatolia quoted Lyor Cohen, the chief executive of the Warner Music Group, …” in Figure 4. For a start position and each target position, the model’s position-attention reflects the importance of each token in determining the head entity type and the relation between entities at the start and target positions. Suppose the start position is at “Lyor”, for a target position at “Warner”, the model should pay more attention to (1) the pattern words “chief executive of” to determine their correct relation type Company_worked, and (2) the entity words “Lyor Cohen” to determine the correct head entity type. This is exactly how attention guidance is built in BR. During BR, for the relation Company_worked, its pattern set contains corresponding patterns, e.g., {‘CEO at’, ‘manager in’, ‘chief executive of’, …} and the BoW will count tokens and their frequencies, e.g., {‘chief’: 8, ‘manager’: 14, ‘executive’: 12, ‘at’: 7, ‘of’: 16, …}. Consequently, the guidance scores for the words “chief”, “executive”, and “of” become large (after softmax computation) as they appear in the BoW with high frequencies. Also, the head entity tokens “Lyor”, and “Cohen” will be given a score of 1. In this way, both “Lyor Cohen” and “chief executive of” will be assigned a high guidance score, and we want the model’s attention to approximate such guidance distribution (by minimizing their MSE distance) so that it can better identify correct relations.
